In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
%run parse.ipynb

In [2]:
# alright, let's try with one movement, one performer!
X = torch.Tensor(parseInputFile('../bach-violin-dataset/dataset/source-input/emil-telmanyi/bwv1002/emil-telmanyi_bwv1002_mov1.csv'))
y = torch.Tensor(parseGroundtruthFile('../bach-violin-dataset/dataset/ground-truth/emil-telmanyi/bwv1002/emil-telmanyi_bwv1002_mov1.csv'))

In [10]:
print(X)
print(y)
print(X.shape)
print(y.shape)

tensor([[   0.,    6.,   78.],
        [   6.,   24.,   59.],
        [   6.,   24.,   66.],
        ...,
        [2262., 2298.,   66.],
        [2262., 2298.,   74.],
        [2262., 2298.,   83.]])
tensor([[1.9200e-01, 9.2800e-01],
        [9.6000e-01, 2.4640e+00],
        [9.6000e-01, 2.4640e+00],
        ...,
        [1.9200e+02, 1.9498e+02],
        [1.9200e+02, 1.9498e+02],
        [1.9200e+02, 1.9498e+02]])
torch.Size([502, 3])
torch.Size([502, 2])


In [11]:
# Starting with linear regression. For this, we only need one linear layer.
# For now, we don't need to build our own module yet because linear regression is simple. However, for an MLP, we will need multiple layers.
model = nn.Linear(3, 2)

In [21]:
# it was retaining nan values for its parameters...
model.reset_parameters()

In [16]:
# Define our loss function (mean squared error) to be used in the grad descent step
loss = nn.MSELoss()

# Performs the gradient descent steps
optimizer = torch.optim.SGD(model.parameters(), lr=1e-6)

In [19]:
# Template code from https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial2/Introduction_to_PyTorch.html#The-Basics-of-PyTorch
def train_model(model, optimizer, input_notes, truth, loss_module, num_epochs=100):
    # Set model to train mode
    model.train()

    # Training loop
    for epoch in range(num_epochs):

        ## Step 1: Move input data to device (only strictly necessary if we use GPU)
        # data_inputs = data_inputs.to(device)
        # data_labels = data_labels.to(device)

        ## Step 2: Run the model on the input data
        preds = model(input_notes)
        print(preds)
        print(model.weight)
        print(model.bias)

        ## Step 3: Calculate the loss
        loss = loss_module(preds, y)
        print(loss)

        ## Step 4: Perform backpropagation
        # Before calculating the gradients, we need to ensure that they are all zero.
        # The gradients would not be overwritten, but actually added to the existing ones.
        optimizer.zero_grad()
        # Perform backpropagation
        loss.backward()

        ## Step 5: Update the parameters
        optimizer.step()

In [22]:
train_model(model, optimizer, X, y, loss)

tensor([[ 9.5449e+00,  2.4803e+01],
        [-2.4040e+00,  1.3912e+01],
        [-1.3621e+00,  1.6356e+01],
        ...,
        [-1.4834e+03,  1.8812e+02],
        [-1.4822e+03,  1.9091e+02],
        [-1.4809e+03,  1.9405e+02]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.2201, -0.4333,  0.1488],
        [ 0.4738, -0.3945,  0.3491]], requires_grad=True)
Parameter containing:
tensor([ 0.5351, -0.0623], requires_grad=True)
tensor(477968.6562, grad_fn=<MseLossBackward0>)
tensor([[  22.2508,   24.5819],
        [  40.6019,   13.2464],
        [  42.0771,   15.6810],
        ...,
        [4495.1460,   99.0084],
        [4496.8315,  101.7908],
        [4498.7285,  104.9210]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[ 1.0874,  0.8795,  0.2107],
        [ 0.4543, -0.4141,  0.3478]], requires_grad=True)
Parameter containing:
tensor([ 0.5360, -0.0623], requires_grad=True)
tensor(3222711., grad_fn=<MseLossBackward0>)
tensor([[-1.0810e+01,  2.5043e+01],
        [-7

In [9]:
X_test = torch.Tensor(parseInputFile('../bach-violin-dataset/dataset/source-input/emil-telmanyi/bwv1001/emil-telmanyi_bwv1001_mov3.csv'))
y_test = torch.Tensor.tolist(model(X_test))

print(model.weight)

X_test = torch.Tensor.tolist(X_test)
print(X_test)
for i in range(len(y_test)):
    y_test[i].append(X_test[i][2])

print(y_test)

Parameter containing:
tensor([[nan, nan, nan],
        [nan, nan, nan]], requires_grad=True)
[[0.0, 18.0, 58.0], [18.0, 24.0, 62.0], [24.0, 36.0, 65.0], [36.0, 42.0, 63.0], [42.0, 48.0, 62.0], [48.0, 54.0, 60.0], [54.0, 60.0, 58.0], [60.0, 72.0, 74.0], [60.0, 72.0, 82.0], [72.0, 84.0, 65.0], [72.0, 84.0, 74.0], [72.0, 84.0, 82.0], [84.0, 96.0, 72.0], [84.0, 96.0, 81.0], [96.0, 108.0, 70.0], [96.0, 108.0, 79.0], [108.0, 120.0, 70.0], [108.0, 120.0, 79.0], [120.0, 132.0, 69.0], [120.0, 132.0, 77.0], [132.0, 144.0, 63.0], [144.0, 156.0, 62.0], [156.0, 168.0, 72.0], [156.0, 168.0, 77.0], [168.0, 180.0, 70.0], [168.0, 180.0, 79.0], [180.0, 192.0, 60.0], [192.0, 198.0, 75.0], [192.0, 204.0, 69.0], [198.0, 204.0, 72.0], [204.0, 216.0, 58.0], [204.0, 216.0, 70.0], [204.0, 216.0, 74.0], [216.0, 228.0, 65.0], [228.0, 234.0, 74.0], [228.0, 246.0, 70.0], [234.0, 240.0, 77.0], [240.0, 246.0, 75.0], [246.0, 252.0, 70.0], [246.0, 252.0, 74.0], [252.0, 264.0, 69.0], [252.0, 264.0, 72.0], [264.0, 276.0